services:
  app.army.handler:
    class: App\Service\CommandBus\Handler\ArmyHandler
    autowire: true
    tags:
      - { name: tactician.handler, typehints: true }

  app.game.handler:
    class: App\Service\CommandBus\Handler\GameHandler
    autowire: true
    tags:
      - { name: tactician.handler, typehints: true }

  League\Tactician\CommandBus: "@tactician.commandbus"